### ISSUE TITLE
Request for Guidance on Using the Project for ZK Proof Generation in Neural Network Training

### ISSUE THREAD

**Issue by AliceRabbit** [jvhs0706/zkdl-train#2]
Dear Sun,

Thank you for sharing your work on this project. I recently began exploring zero-knowledge proofs and found your paper _zkDL: Efficient Zero-Knowledge Proofs of Deep Learning Training_  & 'zkdl-train' repository. The potential applications of this project are fascinating, and I am eager to experiment with it.

However, as someone relatively new to this area of research, particularly with limited experience in CUDA development, I have found it challenging to get started. I fully understand that your primary focus is on research, and you may not have the time to provide extensive support for this project. If it's not too much trouble, could you please offer some brief guidance or suggest any simple modifications to help me better understand how to use the project for generating zero-knowledge proofs during neural network training?

I would greatly appreciate any advice or pointers you could share, and I completely understand if your schedule does not allow for a detailed response.

Thank you for considering my request.

Best regards,
Henry Lu

**Comment by jvhs0706** [comment]
The paper is not yet published. A systematic update of this repo is planned after the publication.
